### PR TITLE
IR Dump format, many filter implementations.

### LINKED ISSUE #3: Fix IR dump to be machine-independent (in seedimg.cpp)
eg. use htonl, etc to convert numbers to endian independant representation in files, same with pixel data

### PR DESCRIPTION
**Pull request by tripulse**
Fixes #3.

### CODE REVIEW

**Comment by tripulse** [comment]
Plus I added, three filters.
Convolution Kernel is fixed to take positive kernels.

**Comment by telugu-boy** [comment]
https://github.com/telugu-boy/seedimg/pull/11/commits/dabf0d26bf937999585503ce27fd000e6da363e4 Put this in a separate namespace `utils` declared in seedimg.hpp.

**Comment by tripulse** [comment]
What about `analytics` namespace?

**Comment by telugu-boy** [comment]
There aren't many analytics to do on images, this isn't a computer vision library

**Comment by tripulse** [comment]
Hm, ok. So, I'll put a couple of commonly used functions this namespace to avoid code duplication, such as — `clamp`, `map`, `to_u32be`.

**Comment by telugu-boy** [comment]
Ok. Not `to_u32be`

**Comment by tripulse** [comment]
Fixed all the merge conflicts. Now @telugu-boy, review and merge.

**Pull request merged**
